In [51]:
import numpy as np
d1 = np.array(['A','1','%'])
print(d1)
d2 = np.arange(0,100,10,dtype=int)
print(d2)
d3 = np.arange(0,100,5).reshape(4,5)
print(d3)
print('\n','dim:',d3.ndim,'\n','shape:',d3.shape,'\n','size:',d3.size)
d4 = np.zeros((3,4))
print(d4)
d5 = np.empty((5,8))
print(d5)


['A' '1' '%']
[ 0 10 20 30 40 50 60 70 80 90]
[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]

 dim: 2 
 shape: (4, 5) 
 size: 20
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [58]:
import numpy as np
d6 = np.linspace(0,100,20).reshape(5,4)
print(d6)
print(d6[1][2])
print(d6[1,2])
print(d6[:,2])
print(d6[2,:])
print(d6[1:3,:])
for row in d6:
    print(row)
for col in d6.T:
    print(col)
print(d6.flatten())
for item in d6.flat:
    print(item)

[[  0.           5.26315789  10.52631579  15.78947368]
 [ 21.05263158  26.31578947  31.57894737  36.84210526]
 [ 42.10526316  47.36842105  52.63157895  57.89473684]
 [ 63.15789474  68.42105263  73.68421053  78.94736842]
 [ 84.21052632  89.47368421  94.73684211 100.        ]]
31.578947368421055
31.578947368421055
[10.52631579 31.57894737 52.63157895 73.68421053 94.73684211]
[42.10526316 47.36842105 52.63157895 57.89473684]
[[21.05263158 26.31578947 31.57894737 36.84210526]
 [42.10526316 47.36842105 52.63157895 57.89473684]]
[ 0.          5.26315789 10.52631579 15.78947368]
[21.05263158 26.31578947 31.57894737 36.84210526]
[42.10526316 47.36842105 52.63157895 57.89473684]
[63.15789474 68.42105263 73.68421053 78.94736842]
[ 84.21052632  89.47368421  94.73684211 100.        ]
[ 0.         21.05263158 42.10526316 63.15789474 84.21052632]
[ 5.26315789 26.31578947 47.36842105 68.42105263 89.47368421]
[10.52631579 31.57894737 52.63157895 73.68421053 94.73684211]
[ 15.78947368  36.84210526  57.

In [126]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.vstack((a,b))
d = np.hstack((a,b))
e = np.concatenate((a,b,b,a),axis=0)
print(a)
print(a.shape)
print(b)
print(c)
print(d)
print(e)
print('\n')
a2 = a[:,np.newaxis]
b2 = b[:,np.newaxis]
c2 = np.vstack((a2,b2))
d2 = np.hstack((a2,b2))
print(a2.shape)
print(b2.shape)
print(c2)
print(d2)


[1 2 3]
(3,)
[4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6 4 5 6 1 2 3]


(3, 1)
(3, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 4]
 [2 5]
 [3 6]]


In [89]:
import numpy as np
d6 = np.linspace(0,100,20).reshape(5,4)
# 等尺寸分割
print(np.split(d6,2,axis=1))
# 不等尺寸分割
print(np.array_split(d6,3,axis=1))
# 纵向等尺寸分割
print(np.vsplit(d6,5))
# 横向等尺寸分割
print(np.hsplit(d6,2))

[array([[ 0.        ,  5.26315789],
       [21.05263158, 26.31578947],
       [42.10526316, 47.36842105],
       [63.15789474, 68.42105263],
       [84.21052632, 89.47368421]]), array([[ 10.52631579,  15.78947368],
       [ 31.57894737,  36.84210526],
       [ 52.63157895,  57.89473684],
       [ 73.68421053,  78.94736842],
       [ 94.73684211, 100.        ]])]
[array([[ 0.        ,  5.26315789],
       [21.05263158, 26.31578947],
       [42.10526316, 47.36842105],
       [63.15789474, 68.42105263],
       [84.21052632, 89.47368421]]), array([[10.52631579],
       [31.57894737],
       [52.63157895],
       [73.68421053],
       [94.73684211]]), array([[ 15.78947368],
       [ 36.84210526],
       [ 57.89473684],
       [ 78.94736842],
       [100.        ]])]
[array([[ 0.        ,  5.26315789, 10.52631579, 15.78947368]]), array([[21.05263158, 26.31578947, 31.57894737, 36.84210526]]), array([[42.10526316, 47.36842105, 52.63157895, 57.89473684]]), array([[63.15789474, 68.42105263, 73.6

In [102]:
import numpy as np
d6 = np.linspace(0,10,6).reshape(3,2)
d7 = d6
# deep copy
d8 = d6.copy()
print(d6)
print(d7)
print(d8)
print('\n')
d6[1:3] = [np.nan]
print(d6)
print(d7)
print(d8)

[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]]
[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]]
[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]]


[[ 0.  2.]
 [nan nan]
 [nan nan]]
[[ 0.  2.]
 [nan nan]
 [nan nan]]
[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]]
